# Generated by Django 2.2.12 on 2021-01-15 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TweetSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.BigIntegerField()),
                ('entity', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('semantic_neg', models.DecimalField(decimal_places=4, max_digits=6, null=True)),
                ('semantic_neu', models.DecimalField(decimal_places=4, max_digits=6, null=True)),
                ('semantic_pos', models.DecimalField(decimal_places=4, max_digits=6, null=True)),
                ('semantic_compound', models.DecimalField(decimal_places=4, max_digits=6, null=True)),
                ('location', models.CharField(max_length=5, null=True)),
            ],
        ),
    ]
