# Generated by Django 2.2.12 on 2021-01-16 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweetsummary',
            name='country_code',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
