# Generated by Django 2.2.12 on 2021-01-16 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_tweetsummary_country_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('semantic_compound', models.DecimalField(decimal_places=4, max_digits=6, null=True)),
            ],
        ),
    ]
