# Generated by Django 2.2.12 on 2021-01-16 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0004_finaltableall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finaltableall',
            name='semantic_compound',
            field=models.DecimalField(decimal_places=5, max_digits=6),
        ),
    ]
