# Generated by Django 2.2.12 on 2021-01-21 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0008_finaltableall_tweet_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweetsummary',
            name='country',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
