# Generated by Django 2.2.12 on 2021-01-21 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0009_tweetsummary_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweetsummary',
            name='continent',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
