# Generated by Django 2.2.12 on 2021-01-23 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0010_tweetsummary_continent'),
    ]

    operations = [
        migrations.AddField(
            model_name='finaltable',
            name='region',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='finaltableall',
            name='semantic_compound',
            field=models.DecimalField(decimal_places=5, max_digits=6, null=True),
        ),
    ]
