# Generated by Django 2.2.12 on 2021-01-23 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0011_auto_20210123_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='finaltable',
            name='tweet_count',
            field=models.IntegerField(default=0),
        ),
    ]
