# Generated by Django 2.2.12 on 2021-01-23 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0012_finaltable_tweet_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finaltable',
            name='semantic_compound',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=6),
        ),
    ]
