# Generated by Django 2.2.12 on 2021-01-24 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0013_auto_20210123_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finaltable',
            name='date',
            field=models.CharField(max_length=30),
        ),
    ]
