# Generated by Django 2.2.12 on 2021-01-24 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0015_auto_20210124_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='finaltable',
            name='semantic_neg',
            field=models.DecimalField(decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='finaltable',
            name='semantic_neu',
            field=models.DecimalField(decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='finaltable',
            name='semantic_pos',
            field=models.DecimalField(decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='finaltableall',
            name='semantic_neg',
            field=models.DecimalField(decimal_places=5, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='finaltableall',
            name='semantic_neu',
            field=models.DecimalField(decimal_places=5, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='finaltableall',
            name='semantic_pos',
            field=models.DecimalField(decimal_places=5, max_digits=6, null=True),
        ),
    ]
