# Generated by Django 2.2.12 on 2021-01-10 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('like_count', models.IntegerField()),
                ('quote_count', models.IntegerField()),
                ('reply_count', models.IntegerField()),
                ('retweet_count', models.IntegerField()),
                ('text', models.CharField(max_length=400)),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twitter.User')),
            ],
        ),
        migrations.CreateModel(
            name='EntityAnnotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_char', models.IntegerField()),
                ('end_char', models.IntegerField()),
                ('probability', models.DecimalField(decimal_places=4, max_digits=6, null=True)),
                ('type', models.CharField(max_length=50)),
                ('normalized_text', models.CharField(max_length=100)),
                ('tweet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twitter.Tweet')),
            ],
        ),
        migrations.CreateModel(
            name='ContextAnnotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_description', models.CharField(max_length=50)),
                ('domain_id', models.BigIntegerField()),
                ('domain_name', models.CharField(max_length=50)),
                ('entity_description', models.CharField(max_length=50)),
                ('entity_id', models.BigIntegerField()),
                ('entity_name', models.CharField(max_length=50)),
                ('tweet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twitter.Tweet')),
            ],
        ),
    ]
