# Generated by Django 2.2.12 on 2021-01-10 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
