# Generated by Django 2.2.12 on 2021-01-10 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0002_auto_20210110_0835'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='TwitterUser',
        ),
    ]
