# Generated by Django 2.2.12 on 2021-01-10 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0003_auto_20210110_0908'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContextAnnotationDomain',
            fields=[
                ('domain_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('domain_description', models.CharField(max_length=50)),
                ('domain_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ContextAnnotationEntity',
            fields=[
                ('entity_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('entity_description', models.CharField(max_length=50)),
                ('entity_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='contextannotation',
            name='domain_description',
        ),
        migrations.RemoveField(
            model_name='contextannotation',
            name='domain_name',
        ),
        migrations.RemoveField(
            model_name='contextannotation',
            name='entity_description',
        ),
        migrations.RemoveField(
            model_name='contextannotation',
            name='entity_name',
        ),
        migrations.AlterField(
            model_name='contextannotation',
            name='domain_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twitter.ContextAnnotationDomain'),
        ),
        migrations.AlterField(
            model_name='contextannotation',
            name='entity_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twitter.ContextAnnotationEntity'),
        ),
    ]
