# Generated by Django 2.2.12 on 2021-01-10 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0004_auto_20210110_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contextannotationentity',
            name='entity_description',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
