# Generated by Django 2.2.12 on 2021-01-10 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0006_auto_20210110_1431'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EntityAnnotation',
            new_name='Entities',
        ),
    ]
