# Generated by Django 2.2.12 on 2021-01-10 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0008_remove_contextannotation_tweet_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='contextannotation',
            name='tweet_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='twitter.Tweet'),
            preserve_default=False,
        ),
    ]
