# Generated by Django 2.2.12 on 2021-01-10 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0009_contextannotation_tweet_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contextannotation',
            name='domain_description',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
