# Generated by Django 2.2.12 on 2021-01-11 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0010_auto_20210110_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='geo',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
