# Generated by Django 2.2.12 on 2021-01-15 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0011_tweet_geo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='date',
            field=models.DateField(default='2020-01-01'),
            preserve_default=False,
        ),
    ]
